# -*- coding: utf-8 -*-
"""CIE-4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-cdkyouRffgViw53V2GyJWbQsgl0JHQl
"""

# Perform Data Pre-processing
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data=pd.read_csv('Mall_Customers.csv')
x=data.iloc[:,[3,4]].values

# Find the optimal numbers of clusters using the elbow method.
from sklearn.cluster import KMeans
wcss_list=[]
for i in range(1,11):
    kmeans=KMeans(n_clusters=i,init='k-means++',random_state=42)
    kmeans.fit(x)
    wcss_list.append(kmeans.inertia_)
plt.plot(range(1,11),wcss_list)
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('Wcss_list')
plt.show()

# Training the K-means algorithm on the training dataset.
kmeans=KMeans(n_clusters=5,init='k-means++',random_state=42)
y_predict=kmeans.fit_predict(x)

#Visualize the Clusters.
plt.scatter(x[y_predict==0,0],x[y_predict==0,1],s=100,c='red',label='Cluster 1')
plt.scatter(x[y_predict==1,0],x[y_predict==1,1],s=100,c='blue',label='Cluster 2')
plt.scatter(x[y_predict==2,0],x[y_predict==2,1],s=100,c='green',label='Cluster 3')
plt.scatter(x[y_predict==3,0],x[y_predict==3,1],s=100,c='purple',label='Cluster 4')
plt.scatter(x[y_predict==4,0],x[y_predict==4,1],s=100,c='pink',label='Cluster 5')
plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],s=300,c='yellow',label='Centroids')
plt.title('Clusters of customers')
plt.xlabel('Annual Income(k$)')
plt.ylabel('Spending Score(1-100)')
plt.legend()
plt.show()